"ci":
  - changed-files:
      - "!.github/labeler.yml"
      - "!.github/labels.json"
      - .github/**/*

"app:appregistry":
  - changed-files:
      - appregistry/**/*

"app:cca":
  - changed-files:
      - cca/**/*

"app:connect":
  - changed-files:
      - connect/**/*

"app:consumer":
  - changed-files:
      - consumer/**/*

"app:examples":
  - changed-files:
      - examples/**/*

"app:explorer":
  - changed-files:
      - explorer/**/*

"app:fee-abstraction":
  - changed-files:
      - fee-abstraction/**/*

"app:hermes":
  - changed-files:
      - hermes/**/*

"app:network":
  - changed-files:
      - network/**/*

"app:evolve":
  - changed-files:
      - evolve/**/*

"app:spaceship":
  - changed-files:
      - spaceship/**/*

"app:wasm":
  - changed-files:
      - wasm/**/*

"configs":
  - changed-files:
      - .gitignore
      - .gitattributes
      - .markdownlint.yaml
      - .golangci.yml
      - app.ignite.yml
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - go.work.example
      - LICENSE
      - Makefile
      - README.md
