"ci":
  - "!.github/labeler.yml"
  - "!.github/labels.json"
  - .github/**/*

"app:appregistry":
  - appregistry/**/*

"app:cca":
  - cca/**/*

"app:connect":
  - connect/**/*

"app:consumer":
  - consumer/**/*

"app:examples":
  - examples/**/*

"app:explorer":
  - explorer/**/*

"app:fee-abstraction":
  - fee-abstraction/**/*

"app:hermes":
  - hermes/**/*

"app:network":
  - network/**/*

"app:rollkit":
  - rollkit/**/*

"app:spaceship":
  - spaceship/**/*

"app:wasm":
  - wasm/**/*

"configs":
  - .gitignore
  - .golangci.yml
  - app.ignite.yml
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - go.work.example
  - LICENSE
  - Makefile
  - README.md
