run:
  tests: false
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - decorder
    - depguard
    - dogsled
    - dupword
    - errchkjson
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - godot
    - gofumpt
    - revive
    - gosimple
    - govet
    - grouper
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - exportloopref
    - staticcheck
    - reassign
    - stylecheck
    - typecheck
    - unconvert
    - tenv
    - thelper
    - unused
    - unparam
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
