run:
  tests: false
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - decorder
    - depguard
    - dogsled
    - dupword
    - errchkjson
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - godot
    - gofumpt
    - gosimple
    - govet
    - grouper
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usetesting

linters-settings:
  forbidigo:
    forbid:
      - p: ^fmt\.Errorf$
        msg: fmt.Errorf should be replaced by '"github.com/ignite/cli/ignite/pkg/errors"'
  depguard:
    rules:
      main:
        deny:
          - pkg: "errors"
            desc: Should be replaced by '"github.com/ignite/cli/ignite/pkg/errors"'
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by '"github.com/ignite/cli/ignite/pkg/errors"'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
