quiet: False
disable-version-string: True
with-expecter: True
all: False
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}.go"
dir: "network/mocks"
outpkg: "mocks"
log-level: debug
recursive: True
packages:
  github.com/ignite/apps/network/network:
    interfaces:
      Chain:
  #      CosmosClient:
  github.com/ignite/apps/network/network/testutil:
    interfaces:
      ProjectClient:
      ProfileClient:
      LaunchClient:
      BankClient:
      RewardClient:
      StakingClient:
      MonitoringcClient:
      MonitoringpClient:
      AccountInfo:
#      IBCClient:
