name: Integration
on:
  pull_request:
  push:
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '**/testdata/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration:
    name: 'Run apps integration tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/*.go
            */go.mod
            */go.sum
      - uses: actions/setup-go@v4
        if: env.GIT_DIFF
        with:
          go-version: '1.21'
      - name: Run Lint Tests
        if: env.GIT_DIFF
        env:
          GOTOOLCHAIN: local+path
          GOSUMDB: off
        run: make test-integration
