name: Integration
on:
  pull_request:
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '**/testdata/**'
  push:
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '**/testdata/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-test:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Finding files and store to output
        id: set-matrix
        run: echo "matrix=$(find . -type d -name "integration" -exec sh -c 'dirname "{}" | cut -c 3-' \; | sort -u | jq -R . | jq -cs .)" >> $GITHUB_OUTPUT

  integration:
    name: ${{ matrix.test-path }}
    runs-on: ubuntu-latest
    needs: pre-test
    if: fromJSON(needs.pre-test.outputs.matrix)[0] != null
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        test-path: ${{fromJson(needs.pre-test.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v6.1.2
        with:
          RELATIVE: ${{ matrix.test-path }}
          PATTERNS: |
            **/*.go
            **/*.plush
            **/*.tpl
            go.mod
            go.sum
            **/testdata/**

      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: '1.23.6'

      - name: Run Integration Tests
        if: env.GIT_DIFF
        env:
          GOTOOLCHAIN: local+path
          GOSUMDB: off
        run: go test -race -failfast -v -timeout 120m ./integration/...
        working-directory: ${{ matrix.test-path }}

  status:
    runs-on: ubuntu-latest
    needs: integration
    if: always()
    steps:
      - name: Update result status
        run: |
          if [ "${{ needs.integration.result }}" = "failure" ]; then
              exit 1
          else
              exit 0
          fi
